#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use App\Command\Firewall\AccessLogCommand;
use App\Command\Firewall\BanIpCommand;
use App\Command\Firewall\BanListCommand;
use App\Command\Firewall\HealthCommand;
use App\Command\Firewall\IgnoredIpsCommand;
use App\Command\Firewall\InitFirewallCommand;
use App\Command\Firewall\IpLookupCommand;
use App\Command\Firewall\ReloadFail2BanCommand;
use App\Command\Firewall\RefreshJailConfigCommand;
use App\Command\Firewall\StatusCommand;
use App\Command\Firewall\UnbanIpCommand;
use App\Command\Firewall\UpdateCloudflareCommand;
use App\Command\Sites\SitesListCommand;
use Symfony\Component\Console\Application;

$application = new Application('Frame Server Tools', '1.0.0');
$application->addCommand(new AccessLogCommand());
$application->addCommand(new BanIpCommand());
$application->addCommand(new BanListCommand());
$application->addCommand(new HealthCommand());
$application->addCommand(new IgnoredIpsCommand());
$application->addCommand(new InitFirewallCommand());
$application->addCommand(new IpLookupCommand());
$application->addCommand(new ReloadFail2BanCommand());
$application->addCommand(new RefreshJailConfigCommand());
$application->addCommand(new SitesListCommand());
$application->addCommand(new StatusCommand());
$application->addCommand(new UnbanIpCommand());
$application->addCommand(new UpdateCloudflareCommand());
$application->run();
