#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use App\Command\AccessLogCommand;
use App\Command\BanIpCommand;
use App\Command\BanListCommand;
use App\Command\HealthCommand;
use App\Command\IgnoredIpsCommand;
use App\Command\InitFirewallCommand;
use App\Command\IpLookupCommand;
use App\Command\ReloadFail2BanCommand;
use App\Command\RefreshJailConfigCommand;
use App\Command\SitesListCommand;
use App\Command\StatusCommand;
use App\Command\UnbanIpCommand;
use App\Command\UpdateCloudflareCommand;
use Symfony\Component\Console\Application;

$application = new Application('Frame Server Tools', '1.0.0');
$application->addCommand(new AccessLogCommand());
$application->addCommand(new BanIpCommand());
$application->addCommand(new BanListCommand());
$application->addCommand(new HealthCommand());
$application->addCommand(new IgnoredIpsCommand());
$application->addCommand(new InitFirewallCommand());
$application->addCommand(new IpLookupCommand());
$application->addCommand(new ReloadFail2BanCommand());
$application->addCommand(new RefreshJailConfigCommand());
$application->addCommand(new SitesListCommand());
$application->addCommand(new StatusCommand());
$application->addCommand(new UnbanIpCommand());
$application->addCommand(new UpdateCloudflareCommand());
$application->run();
